package org.livingplace.activitylearning.event;

public enum FunctionalSpaceLabel {

	KITCHEN,
	KITCHEN_COOKING,
	KITCHEN_SHELF,
	KITCHEN_SINK,
	KITCHEN_COFFEEMACHINE,
	KITCHEN_FRIDGE,
	BATHROOM,
	BATHROOM_TOILET,
	BATHROOM_SINK,
	BATHROOM_SHOWER,
	DININGROOM,
	DININGROOM_TABLE,
	DININGROOM_TOUCHTABLE,
	BEDROOM,
	BEDROOM_BED,
	BEDROOM_CLOSET,
	LOUNGE,
	LOUNGE_COUCH,
	HALLWAY,
	HALLWAY_ENTRANCE,
	UNDEFINED;
}
